config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
get '/users/edit' =>'users#edit'

  get '/users' => 'users#index'

  get '/easter' => 'users#easter', :as => "easter"

  get '/users/profile' => 'users#profile'
  get '/admin' => 'pages#admin', :as => "admin"
  get '/map' => 'pages#map', :as => "map"
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  resources :users, :only => [:new, :create, :update, :show] do
    member do
          get :following, :followers
        end
  end
  resources :posts, :only => [:create, :destroy] do
    resources :comments

  end
  post '/posts/:post_id/likes' => 'likes#create', :as => "likes"
  delete '/posts/:post_id/likes' => 'likes#destroy'
  resources :relationships, :only => [:create, :destroy]
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  message    :text
#  post_id    :integer
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  default_scope { order(created_at: :desc) }
  validates :message, :presence => true, :length => { :maximum => 140}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @user = @current_user
    @post = Post.find params[:post_id]
    @user_post = @post.user
    @comment = Comment.new
    render :index, :layout => false
  end

  def create
    @post = Post.find params[:post_id]
    @comment = @post.comments.new comment_params
    @comment.user_id = @current_user.id
    if @comment.save
      redirect_to request.referrer || root_path
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to :back
  end

  private
  def comment_params
      params.require(:comment).permit(:message, :user_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% @post.comments.each do |comment| %>
  <div class="comment-box">
    <h4><%= comment.user.name %> <small><%=  "#{time_ago_in_words(comment.created_at)} ago"%></small></h4>

    <p><%= comment.message %></p>

    <div class="icons">
      <% if @current_user == comment.user %>
        <%= link_to post_comment_path(:post_id => @post.id,:id => comment.id), :method => 'delete', :data => { :confirm => 'Are you sure?'} do%><i class="glyphicon glyphicon-trash" aria-hidden="true"></i><% end %>
      <% end %>
    </div>

  </div>
<% end %>

app/views/comments/_index.html.erb
<div class="row feed_box_modal">

  <div class="col-md-2 feed-image-col">
    <div style='background-image: url(<%= "http://res.cloudinary.com/kryx11/image/upload/#{@post.user.image}"%>)', class="thumbBox"></div>
  </div>

  <div class="col-md-10 feed-tweet comment-tweet">
    <h4><%= @user_post.name %> <small class= "feed_time"> <%= "#{time_ago_in_words(@post.created_at)} ago" unless @post.created_at.nil? %></small></h4>

    <p><%= @post.tweet %></p>

    <div class="icons">
      <% if @current_user == @post.user %>
        <%= link_to post_path(:id => @post.id),:method => 'delete', :data => { :confirm => 'Are you sure?'} do%><i class="glyphicon glyphicon-trash" aria-hidden="true"></i><% end %>
      <% end %>
    </div>

  </div>
</div>

<%= form_for [@post, @comment] do |f| %>
  <div class="form-group comment-form">
    <%= f.text_area :message, placeholder: "Comment...", :required => true, :class => "form-control comment-input" %>
  </div>
  <%= f.submit "Comment", :class => 'btn btn-primary comment-button'%>
<% end %>

app/views/comments/index.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="myModalLabel">Leave a comment</h4>
</div>

<div class="modal-body">
  <%=  render :partial => 'comments/index' %>
  <%=  render :partial => 'comments/comment' %>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>