config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
get '/users/edit' =>'users#edit'

  get '/users' => 'users#index'

  get '/easter' => 'users#easter', :as => "easter"

  get '/users/profile' => 'users#profile'
  get '/admin' => 'pages#admin', :as => "admin"
  get '/map' => 'pages#map', :as => "map"
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  resources :users, :only => [:new, :create, :update, :show] do
    member do
          get :following, :followers
        end
  end
  resources :posts, :only => [:create, :destroy] do
    resources :comments

  end
  post '/posts/:post_id/likes' => 'likes#create', :as => "likes"
  delete '/posts/:post_id/likes' => 'likes#destroy'
  resources :relationships, :only => [:create, :destroy]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  tweet      :text
#  likes      :integer          default("0")
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  default_scope { order(created_at: :desc) }
  validates :tweet, :presence => true, :length => { :maximum => 140}
  has_many :likes

  def likeit(like_user)
      likes.create(user_id: like_user.id )
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_if_logged_in, :only => [:create, :destroy]

  def create
    @user = @current_user
    @post = @user.posts.new post_params
    @user_feed= @current_user.feed
    if @post.save
      redirect_to root_path
    else
      render "pages/home"
    end

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:user_id, :tweet, :likes)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="feed-container">

  <% @user_feed.each do |post| %>
    <div class="row feed_box">

      <div class="col-md-2 feed-image-col">
        <%= link_to user_path(:id=>post.user.id), :method=>'get' do%>
          <div style='background-image: url(<%= "http://res.cloudinary.com/kryx11/image/upload/#{post.user.image}"%>)', class="thumbBox"></div>
        <% end %>
      </div>

      <div class="col-md-10 feed-tweet">
        <h4 class= "feed_username"><%= post.user.name %></h4><small class= "feed_time"><%= "#{time_ago_in_words(post.created_at)} ago" unless post.created_at.nil? %></small>
        <p><%= post.tweet %></p>

        <div class="icons">
          <% if @current_user.likes.where(:post_id => post.id).count > 0 %>
              <%= link_to likes_path(:post_id => post.id), :method => 'delete' do%><i class="glyphicon glyphicon-heart"></i><% end %>
          <% else %>
              <%= link_to likes_path(:post_id => post.id), :method => 'post' do%><i class="glyphicon glyphicon-heart"></i><% end %>
          <% end %>
          <%= post.likes.count %>
        </div>

        <div class="icons">
          <%= link_to post_comments_path(post,@comment), data: {toggle: "modal", target: "#myModal"} do%><i class="glyphicon glyphicon-comment" aria-hidden="true"></i><% end %>
          <%= post.comments.count %>
        </div>

        <div class="icons">
          <% if @current_user == post.user %>
            <%= link_to post_path(:id => post.id),:method => 'delete', :data => { :confirm => 'Are you sure?'} do%><i class="glyphicon glyphicon-trash" aria-hidden="true"></i><% end %>
          <% end %>
        </div>

      </div>
    </div>
  <% end %>

</div>

app/views/posts/_post_form.html.erb
<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <p class="bg-warning"><%= msg %></p>
    <% end %>
<% end %>

<div class="post-form-container">
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :tweet , :class => "sr-only"%>
      <%= f.text_area :tweet, placeholder: "What's new?", :required => true, :class => "form-control" %>
    </div>
    <%= f.submit "Tweet", :class => 'btn btn-primary'%>
  <% end %>
</div>