config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
get '/users/edit' =>'users#edit'

  get '/users' => 'users#index'

  get '/easter' => 'users#easter', :as => "easter"

  get '/users/profile' => 'users#profile'
  get '/admin' => 'pages#admin', :as => "admin"
  get '/map' => 'pages#map', :as => "map"
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  resources :users, :only => [:new, :create, :update, :show] do
    member do
          get :following, :followers
        end
  end
  resources :posts, :only => [:create, :destroy] do
    resources :comments

  end
  post '/posts/:post_id/likes' => 'likes#create', :as => "likes"
  delete '/posts/:post_id/likes' => 'likes#destroy'
  resources :relationships, :only => [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>TwitterClone</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= cloudinary_js_config %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
<body>

  <!-- BOOTSTRAP -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" >Twitter<small>s.</small></a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path %></a></li>
          <% if @current_user.present? %>
            <li><%= link_to "Edit Profile", users_edit_path %></li>
            <li><%= link_to "All users", users_path %></li>
            <li><%= link_to "Following", following_user_path(@current_user) %></li>
            <li><%= link_to "Followers", followers_user_path(@current_user) %></li>
            <li><%= link_to "Map", map_path %></li>

            <% if @current_user.admin? %>
              <li><%= link_to "Admin page", admin_path %></li>
            <% end %>
          <% end %>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if @current_user.present? %>
            <li><%= link_to "Logout #{@current_user.name || @current_user.email }", login_path, :method => 'delete' %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_path %></li>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
  <%= yield %>
  </div>
  
</body>
</html>